name: "Push Docker image to DockerHub"
#buat ngetest docker hub 
#test push image

on:
  push:
    branches: [ main ]
           

jobs:
  push_to_registry:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo 
        uses: actions/checkout@v2

      - name: Publish docker image
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker build -t enjangse/goapp:tugasbesar .
          docker push enjangse/goapp:tugasbesar
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/enjang/web-example-golang
            ls -lah
            docker rm -f goapp && docker rmi enjangse/goapp:tugasbesar
            docker-compose -f docker-compose.yml up -d
